island:
  countHorizontalCeil: 10
  countVerticalCeil: 10
  sizeCeil: 50
  start:
    count:
      wolf: 5
      rabbit: 5

server:
  port: 8008

spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/static/
    encoding: UTF-8
    servlet:
      content-type: text/html

entity:
  view:
    wolf: ğŸº
    rabbit: ğŸ°